# Generated by Django 4.2.7 on 2026-01-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('site_name', models.CharField(default='My AI Store', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='themes/logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='themes/favicons/')),
                ('primary_color', models.CharField(default='#6366f1', max_length=20)),
                ('secondary_color', models.CharField(default='#4f46e5', max_length=20)),
                ('accent_color', models.CharField(default='#f59e0b', max_length=20)),
                ('background_color', models.CharField(default='#ffffff', max_length=20)),
                ('text_color', models.CharField(default='#1e293b', max_length=20)),
                ('heading_font', models.CharField(default='Inter', max_length=100)),
                ('body_font', models.CharField(default='Inter', max_length=100)),
                ('heading_size', models.CharField(default='2.5rem', max_length=10)),
                ('body_size', models.CharField(default='1rem', max_length=10)),
                ('font_weight_bold', models.IntegerField(default=700)),
                ('font_weight_normal', models.IntegerField(default=400)),
                ('line_height', models.CharField(default='1.6', max_length=10)),
                ('border_radius', models.CharField(default='12px', max_length=10)),
                ('button_radius', models.CharField(default='8px', max_length=10)),
                ('card_shadow', models.CharField(default='0 4px 12px rgba(0,0,0,0.1)', max_length=100)),
                ('spacing_unit', models.CharField(default='1rem', max_length=10)),
                ('container_width', models.CharField(default='1280px', max_length=10)),
                ('banner_text', models.CharField(default='Find Everything You Need with AI', max_length=500)),
                ('banner_subtext', models.CharField(default='Experience the future of shopping with our zero-human automated platform.', max_length=500)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='themes/banners/')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Theme Settings',
            },
        ),
    ]
