# Generated by Django 4.2.7 on 2026-01-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='body_line_height',
            field=models.CharField(default='1.6', max_length=10),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='button_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='button_style',
            field=models.CharField(choices=[('solid', 'Solid'), ('outline', 'Outline'), ('ghost', 'Ghost')], default='solid', max_length=20),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='dark_background',
            field=models.CharField(default='#0f172a', max_length=20),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='dark_text',
            field=models.CharField(default='#f1f5f9', max_length=20),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='enable_dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='enable_gradients',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='footer_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='header_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='heading_line_height',
            field=models.CharField(default='1.2', max_length=10),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='hero_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='hero_gradient',
            field=models.CharField(default='linear-gradient(135deg, #f59e0b 0%, #f97316 100%)', max_length=200),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='letter_spacing',
            field=models.CharField(default='0px', max_length=10),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='primary_gradient',
            field=models.CharField(default='linear-gradient(135deg, #6366f1 0%, #4f46e5 100%)', max_length=200),
        ),
    ]
